var diccCatalan = {
    "infocoordinatescontrol":{
        "title": "aaaaaaaaaaaaaaaaaa",
        "point": "b",
        "datum": "b",
        "latitude": "b",
        "longitude": "b",
        "formatCoordinates": "b",
        "coordX": "b",
        "coordY": "b",
        "altitude": "b",
        "removePoint": "b",
        "removeAllPoints": "b",
        "importAllPoints": "b",
        "displayONAllPoints": "b",
        "displayOFFAllPoints": "b",
    },
    "location":{
        "error": "El control ubicació no accepta http. Ha d'usar https.",
        "title": "Obtindre ubicació actual"
    },
    "layerswitcher":{
        "title": "Selector de capes"
    },
    "scale":{
        "title": "Escala",
        "scale": "Escala",
        "level": "Nivell"
    },
    "getfeatureinfo":{
        "info": "Informació",
        "title": "Consultar capa",
        "no_info": "No existeix informació associada",
        "info_of": "Informació de",
        "unsupported_format": "Format no suportat"
    },
    "wmcselector":{
        "title": "Selector de contextos"
    },
    "rotate":{
        "title": "Girar al nord"
    },
    "mouse":{
        "title": "Coordenades del punter"
    },
    "dialog":{
        "info": "INFORMACIÓ",
        "error": "ERROR",
        "success": "ÈXIT",
        "id_feature": "No s'ha indicat un ID per a obtindre el feature",
        "invalid_type_layer": "No s'ha especificat un tipus vàlid per a la capa",
        "vector_filter": "El filtre indicat no és correcte",
        "unauthorized_user": "Ha ocorregut un error en carregar la capa: Usuari no autoritzat.",
        "only_one_filter": "FeatureID i CQL són mútuament excloents. Indicar només un tipus de filtrat.",
        "any_format": "TXT, ni HTML ni GML estan suportats"
    },
    "feature":{
        "incorrect_attributes": "No s'han especificat correctament els atributs."
    },
    "exception":{
        "addto_method": "La implementació usada no posseeix el mètode addTo",
        "getelement_method": "La implementació usada no posseeix el mètode getElement",
        "getfeatureinfo_method": "La implementació usada no pot crear controls GetFeatureInfo",
        "mouse_method": "La implementació usada no pot crear controls Mouse",
        "navtoolbar_method": "La implementació usada no pot crear controls Navtoolbar",
        "overviewmap_method": "La implementació usada no pot crear controls OverviewMap",
        "panzoom_method": "La implementació usada no pot crear controls Panzoom",
        "panzoombar_method": "La implementació usada no pot crear controls Panzoombar",
        "scale_method": "La implementació usada no pot crear controls Scale",
        "scaleline_method": "La implementació usada no pot crear controls ScaleLine",
        "wmcselector_method": "La implementació usada no pot crear controls WMCSelector",
        "geojson_method": "La implementació usada no pot crear objectes M.impl.format.GeoJSON",
        "wkt_method": "La implementació usada no pot crear objectes M.impl.format.WKT",
        "getfeaturesbylayer_method": "La implementació usada no posseeix el mètode getFeaturesByLayer",
        "geojsonlayer_method": "La implementació usada no pot crear capes GeoJSON",
        "no_param": "No s'ha especificat cap paràmetre",
        "no_name": "No ha especificat cap nom",
        "kmllayer_method": "La implementació usada no pot crear capes KML",
        "isvisible_method": "La implementació usada no posseeix el mètode isVisible",
        "isqueryable_methd": "La implementació usada no posseeix el mètode isQueryable",
        "visibility_param": "No ha especificat cap paràmetre de visibilitat",
        "setvisible_method": "La implementació usada no posseeix el mètode setVisible",
        "inrange_method": "La implementació usada no posseeix el mètode inRange",
        "mapbox_method": "La implementació usada no pot crear capes Mapbox",
        "osm_method": "La implementació usada no pot crear capes OSM",
        "vectorlayer_method": "La implementació usada no pot crear capes Vector",
        "wfslayer_method": "La implementació usada no pot crear capes WFS",
        "wmclayer_method": "La implementació usada no pot crear capes WMC",
        "select_method": "La implementació usada no posseeix el mètode select",
        "unselect_method": "La implementació usada no posseeix el mètode unselect",
        "constructor_impl": "La implementació usada no posseeix un constructor.",
        "getlayers_method": "La implementació usada no posseeix el mètode getLayers.",
        "getbaselayers_method": "La implementació usada no posseeix el mètode getBaseLayers.",
        "addlayers_method": "La implementació usada no posseeix el mètode addLayers.",
        "removelayers_method": "La implementació usada no posseeix el mètode removeLayers.",
        "getwmc_method": "La implementació usada no posseeix el mètode getWMC.",
        "addwmc_method": "La implementació usada no posseeix el mètode addWMC.",
        "removewmc_method": "La implementació usada no posseeix el mètode removeWMC.",
        "getkml_method": "La implementació usada no posseeix el mètode getKML.",
        "addkml_method": "La implementació usada no posseeix el mètode addKML.",
        "removekml_method": "La implementació usada no posseeix el mètode removeKML.",
        "getwms_method": "La implementació usada no posseeix el mètode getWMS.",
        "addwms_method": "La implementació usada no posseeix el mètode addWMS.",
        "removewms_method": "La implementació usada no posseeix el mètode removeWMS.",
        "getwfs_method": "La implementació usada no posseeix el mètode getWFS.",
        "getgeojson_method": "La implementació usada no posseeix el mètode getGeoJSON.",
        "addwfs_method": "La implementació usada no posseeix el mètode addWFS.",
        "removewfs_method": "La implementació usada no posseeix el mètode removeWFS.",
        "getwmts_method": "La implementació usada no posseeix el mètode getWMTS.",
        "addwmts_method": "La implementació usada no posseeix el mètode addWMTS.",
        "removewmts_method": "La implementació usada no posseeix el mètode removeWMTS.",
        "getmbtiles_method": "La implementació usada no posseeix el mètode getMBtiles.",
        "getxyzs_method": "La implementació usada no posseeix el mètode getXYZs.",
        "gettms_method": "La implementació usada no posseeix el mètode getTMS.",
        "getcontrols_method": "La implementació usada no posseeix el mètode getControls.",
        "addcontrols_method": "La implementació usada no posseeix el mètode addControls.",
        "remove_control": "No ha especificat cap control a eliminar.",
        "removecontrol_method": "La implementació usada no posseeix el mètode removeControls.",
        "setmaxextent_method": "La implementació usada no posseeix el mètode setMaxExtent.",
        "getbbox_method": "La implementació usada no posseeix el mètode getBbox.",
        "no_bbox": "No ha especificat cap bbox.",
        "setbbox_method": "La implementació usada no posseeix el mètode getBbox.",
        "incorrect_bbox_format": "El format del paràmetre bbox no és el correcte.",
        "getzoom_method": "La implementació usada no posseeix el mètode getZoom.",
        "no_zoom": "No ha especificat cap zoom.",
        "setzoom_method": "La implementació usada no posseeix el mètode setZoom.",
        "getcenter_method": "La implementació usada no posseeix el mètode getCenter.",
        "setcenter_method": "La implementació usada no posseeix el mètode setCenter.",
        "getresolutions_method": "La implementació usada no posseeix el mètode getResolutions.",
        "no_resolutions": "No ha especificat cap resolució.",
        "setresolutions_method": "La implementació usada no posseeix el mètode setResolutions.",
        "getscale_method": "La implementació usada no posseeix el mètode getScale.",
        "getprojection_method": "La implementació usada no posseeix el mètode getProjection.",
        "no_projection": "No ha especificat cap projecció.",
        "setprojection_method": "La implementació usada no posseeix el mètode setProjection.",
        "no_plugins": "No ha especificat cap plugin.",
        "no_add_plugin_to_map": "El plugin no pot afegir-se al mapa.",
        "no_plugin_to_remove": "No ha especificat cap plugin a eliminar.",
        "destroy_method": "La implementació usada no posseeix el mètode destroy.",
        "addlabel_method": "La implementació usada no posseeix el mètode addLabel.",
        "no_point": "No ha especificat cap punt.",
        "remove_control_from_panel": "Ha d'eliminar els controls del panell prèviament.",
        "getcontainer_method": "La implementació usada no posseeix el mètode getContainer.",
        "getmapimpl_method": "La implementació usada no posseeix el mètode getMapImpl.",
        "removepopup_method": "La implementació usada no posseeix el mètode removePopup.",
        "no_popup": "No ha especificat cap popup.",
        "invalid_popup": "El popup especificat no és vàlid.",
        "no_maxextent": "No ha especificat cap maxExtent",
        "must_be_document": "doc.nodeType ha de ser de tipus DOCUMENT",
        "no_service_response": "No va haver-hi resposta del servei",
        "no_kml_response": "No va haver-hi resposta del KML",
        "no_getfeature_response": "No va haver-hi resposta en l'operació GetFeature",
        "no_map": "No ha especificat cap mapa",
        "layerswitcher_method": "La implementació usada no pot crear controls LayerSwitcher",
        "location_method": "La implementació usada no pot crear controls Location",
        "wms_method": "La implementació usada no pot crear capes WMS",
        "wmts_method": "La implementació usada no pot crear capes WMTS",
        "no_impl": "No s'ha especificat cap implementació",
        "no_container": "No ha especificat cap paràmetre contenidor",
        "no_id_container": "No existeix cap contenidor amb l’ID especificat",
        "no_center": "No ha especificat cap paràmetre center",
        "no_attr_name": "No s'ha especificat el nom de l'atribut",
        "no_empty": "El nom d'atribut no pot ser nul. Especifique cadena o funció",
        "invalid_center_param": "El format del paràmetre center no és correcte",
        "invalid_maxextent_param": "El format del paràmetre maxExtent no és correcte",
        "invalid_resolutions_param": "El format del paràmetre resolutions no és correcte",
        "invalid_zoom_param": "El format del paràmetre zoom no és correcte",
        "min_gt_max": "No pot establir-se un radi mínim major que el màxim.",
        "max_lt_min": "No pot establir-se un radi màxim menor que el mínim.",
        "no_geojson": "No s'ha especificat cap GeoJSON",
        "unsupported_lang": "S'ha establit un idioma sense suport"
    },
    "cambioIdioma":{
        "esp": "Espanyol",
        "ing": "Anglés",
        "cat": "català",
        "gal": "gallec",
        "eus": "euskera",
        "contenedor": "Canvi d'idioma",
        "divIdioma": "Idioma del visualitzador"
    }
}

