var diccEuskera = {				
    "location":{			
        "error":"Kokapen kontrolak ez du http onartzen. https erabili behar duzu.",			
        "title":"Lortu uneko kokapena",			
    },				
    "layerswitcher":{			
        "title":"geruza-hautatzailea",			
    },				
    "scale":{			
        "title":"Eskala",			
        "scale":"Eskala",			
        "level":"Maila",			
    },				
    "getfeatureinfo":{			
        "info":"Informazioa",			
        "title":"Geruza kontsultatu",			
        "no_info":"Ez dago erlazionatutako informaziorik",			
        "info_of":"ren informazioa",			
        "unsupported_format":"Ez da formatua onartzen",			
    },				
    "wmcselector":{			
        "title":"Testuinguruen hautatzailea",			
    },				
    "rotate":{			
        "title":"Iparraldera biratu",			
    },				
    "mouse":{			
        "title":"Erakuslearen koordenatuak",			
    },				
    "dialog":{			
        "info":"INFORMAZIOA",			
        "error":"ERROREA",			
        "success":"ARRAKASTA",			
        "id_feature":"Ez da ID bat adierazi featurea lortzeko",			
        "invalid_type_layer": "Ez da zehaztu geruzarako balio egokia",
        "vector_filter":"Adierazitako iragazkia ez da zuzena",			
        "unauthorized_user":"Errorea gertatu da geruza kargatzean",		
        "only_one_filter":"FeatureID eta CQL elkarrekiko baztertzaileak dira. Iragazte-mota bakarra adierazi.",			
        "any_format":"TXT, ez HTML ez GML ez daude jasanda",			
    },				
    "feature":{			
        "incorrect_attributes":"Ezaugarriak ez dira behar bezala zehaztu.",			
    },				
    "exception":{			
        "addto_method":"Erabilitako inplementazioak ez du addTo metodoa",			
        "getelement_method":"Erabilitako inplementazioak ez du getElement metodoa",			
        "getfeatureinfo_method":"Erabilitako implementazioak ezin du GetFeatureInfo kontrolik sortu",		
        "mouse_method":"Erabilitako implementazioak ezin du Mouse kontrolik sortu",			
        "navtoolbar_method":"Erabilitako implementazioak ezin du NavToolbar kontrolik sortu",		
        "overviewmap_method":"Erabilitako inplementazioak ezin ditu OverviewMap kontrolak sortu",		
        "panzoom_method":"Erabilitako inplementazioak ezin du Panzoom kontrolik sortu",			
        "panzoombar_method":"Erabilitako inplementazioak ezin ditu Panzoombar kontrolak sortu",			
        "scale_method":"Erabilitako inplementazioak ezin ditu Scale kontrolak sortu",			
        "scaleline_method":"Erabilitako inplementazioak ezin ditu ScaleLine kontrolak sortu",			
        "wmcselector_method":"Erabilitako ezarpenak ezin ditu WMCSelector kontrolak sortu",			
        "geojson_method":"Erabilitako inplementazioak ezin ditu M.impl.format.GeoJSON objektuak sortu.  ",			
        "wkt_method":"Erabilitako inplementazioak ezin ditu M.impl.format.WKT objektuak sortu.",			
        "getfeaturesbylayer_method":"Erabilitako inplementazioak ez du getFeaturesByLayer metodoa",			
        "geojsonlayer_method":"Erabilitako inplementazioak ezin ditu GeoJSON geruzak sortu",			
        "no_param":"Ez da parametrorik zehaztu",			
        "no_name":"Ez duzu izenik zehaztu",			
        "kmllayer_method":"Erabilitako inplementazioak ezin ditu KML geruzak sortu",			
        "isvisible_method":"Erabilitako inplementazioak ez du metodo isVisible",			
        "isqueryable_methd":"Erabilitako inplementazioak ez du metodo isqueryablea",			
        "visibility_param":"Ez duzu ikuspen-parametrorik zehaztu",			
        "setvisible_method":"Erabilitako inplementazioak ez du setVisible metodorik",			
        "inrange_method":"Erabilitako inplementazioak ez du inRange metodoa",			
        "mapbox_method":"Erabilitako inplementazioak ezin ditu Mapbox geruzak sortu",			
        "osm_method":"Erabilitako inplementazioak ezin ditu OSM geruzak sortu",			
        "vectorlayer_method":"Erabilitako inplementazioak ezin ditu Vector geruzak sortu",			
        "wfslayer_method":"Erabilitako inplementazioak ezin ditu WFS geruzak sortu",			
        "wmclayer_method":"Erabilitako inplementazioak ezin ditu WMC geruzak sortu",			
        "select_method":"Erabilitako inplementazioak ez du select metodoa",			
        "unselect_method":"Inplementazio erabiliak ez du unselect metodoa",			
        "constructor_impl":"Erabilitako inplementazioak ez du eraikitzailerik. ",			
        "getlayers_method":"Erabilitako inplementazioak ez du getLayers metodoa. ",			
        "getbaselayers_method":"Erabilitako inplementazioak ez du getBaseLayers metodoa. ",			
        "addlayers_method":"Erabilitako inplementazioak ez du addLayers metodoa. ",			
        "removelayers_method":"Erabilitako inplementazioak ez du removeLayers metodoa. ",			
        "getwmc_method":"Erabilitako inplementazioak ez du getWMC metodoa",			
        "addwmc_method":"Erabilitako inplementazioak ez du addWMC metodoa",			
        "removewmc_method":"Erabilitako inplementazioak ez du removeWMC metodoa",			
        "getkml_method":"Erabilitako inplementazioak ez du getKML metodoa.",			
        "addkml_method":"Erabilitako inplementazioak ez du addKML metodoa.",			
        "removekml_method":"Erabilitako inplementazioak ez du removeKML metodoa.",			
        "getwms_method":"Erabilitako inplementazioak ez du getWMS metodoa.",			
        "addwms_method":"Erabilitako inplementazioak ez du addWMS metodoa.",			
        "removewms_method":"Erabilitako inplementazioak ez du removeWMS metodoa.",			
        "getwfs_method":"Erabilitako inplementazioak ez du getWFS metodoa.",			
        "getgeojson_method":"Erabilitako inplementazioak ez du getGeoJSON metodoa.",			
        "addwfs_method":"Erabilitako inplementazioak ez du addWFS metodoa.",			
        "removewfs_method":"Erabilitako inplementazioak ez du removeWFS metodoa.",			
        "getwmts_method":"Erabilitako inplementazioak ez du getWMTS metodoa.",			
        "addwmts_method":"Erabilitako inplementazioak ez du addWMTS metodoa.",			
        "removewmts_method":"Erabilitako inplementazioak ez du removeWMTS metodoa.",			
        "getmbtiles_method":"Erabilitako inplementazioak ez du getMBtiles metodoa. ",			
        "getxyzs_method":"Erabilitako inplementazioak ez du getXYZs metodoa. ",			
        "gettms_method":"Erabilitako inplementazioak ez du getTMS metodoa.",			
        "getcontrols_method":"Erabilitako inplementazioak ez du getControls metodoa. ",			
        "addcontrols_method":"Erabilitako inplementazioak ez du addControls metodoa. ",			
        "remove_control":"Ez duzu ezabatu beharreko kontrolik zehaztu. ",			
        "removecontrol_method":"Erabilitako inplementazioak ez du removeControls metodoa. ",			
        "setmaxextent_method":"Erabilitako inplementazioak ez du setMaxExtent metodoa. ",			
        "getbbox_method":"Erabilitako inplementazioak ez du getBbox metodoa. ",			
        "no_bbox":"Ez duzu bboxik zehaztu. ",			
        "setbbox_method":"Erabilitako inplementazioak ez du setBbox metodoa. ",			
        "incorrect_bbox_format":"Ez da zuzena bbox parametroaren formatua. ",			
        "getzoom_method":"Erabilitako inplementazioak ez du getZoom metodoa. ",			
        "no_zoom":"Ez duzu zoomik zehaztu. ",			
        "setzoom_method":"Erabilitako inplementazioak ez du setZoom metodoa. ",			
        "getcenter_method":"Erabilitako inplementazioak ez du getCenter metodoa. ",			
        "setcenter_method":"Erabilitako inplementazioak ez du setCenter metodoa. ",			
        "getresolutions_method":"Erabilitako inplementazioak ez du getResolutions metodoa. ",			
        "no_resolutions":"Ez du bereizmenik zehaztu. ",			
        "setresolutions_method":"Erabilitako inplementazioak ez du setResolutions metodoa. ",			
        "getscale_method":"Erabilitako inplementazioak ez du getScale metodoa. ",			
        "getprojection_method":"Erabilitako inplementazioak ez du getProjection metodoa. ",			
        "no_projection":"Ez duzu proiekziorik zehaztu. ",			
        "setprojection_method":"Erabilitako inplementazioak ez du setProjection metodoa. ",			
        "no_plugins":"Ez duzu pluginik zehaztu. ",			
        "no_add_plugin_to_map":"Plugina ezin zaio mapari erantsi. ",			
        "no_plugin_to_remove":"Ez duzu ezabatu beharreko pluginik zehaztu. ",			
        "destroy_method":"Erabilitako inplementazioak ez du destroy metodoa. ",			
        "addlabel_method":"Erabilitako inplementazioak ez du addLabel metodoa. ",			
        "no_point":"Ez duzu punturik zehaztu. ",			
        "remove_control_from_panel":"Paneleko kontrolak ezabatu behar dituzu aldez aurretik. ",			
        "getcontainer_method":"Erabilitako inplementazioak ez du getContainer metodoa. ",			
        "getmapimpl_method":"Erabilitako inplementazioak ez du getMapImpl metodoa. ",			
        "removepopup_method":"Erabilitako inplementazioak ez du removePopup metodoa. ",			
        "no_popup":"Ez duzu popup bat ere zehaztu. ",			
        "invalid_popup":"Zehaztutako popup-ak ez du balio. ",			
        "no_maxextent":"Ez duzu maxExtent bat ere zehaztu",			
        "must_be_document":"Doc.nodeType DOCUMENT motakoa izan behar da",			
        "no_service_response":"Zerbitzuaren erantzunik ez dago",			
        "no_kml_response":"KMLren erantzunik ez",			
        "no_getfeature_response":"GetFeature operazioan erantzunik ez",			
        "no_map":"Ez duzu maparik zehaztu",			
        "layerswitcher_method":"Erabilitako inplementazioak ezin du LayerSwitcher kontrolik sortu",			
        "location_method":"Erabilitako inplementazioak ezin du Location kontrolik sortu",			
        "wms_method":"Erabilitako inplementazioak ezin ditu WMS geruzak sortu",			
        "wmts_method":"Erabilitako inplementazioak ezin ditu WMTS geruzak sortu",			
        "no_impl":"Ez da inplementaziorik zehaztu",			
        "no_container":"Ez duzu parametro edukiontzirik zehaztu",			
        "no_id_container":"Ez dago zehaztutako IDa duen edukiontzirik",			
        "no_center":"Ez duzu center parametrorik zehaztu",			
        "no_attr_name":"Ez da zehaztu atributuaren izena",			
        "no_empty":"Atributuaren izena ezin da baliogabea izan. Zehaztu katea edo funtzioa ",			
        "invalid_center_param":"Center parametroaren formatua ez da zuzena",			
        "invalid_maxextent_param":"MaxExtent parametroaren formatua ez da zuzena",			
        "invalid_resolutions_param":"Resolutions parametroaren formatua ez da zuzena",			
        "invalid_zoom_param":"Zoom parametroaren formatua ez da zuzena",			
        "min_gt_max":"Erradio minimoa ezin da maximoa baino handiagoa ezarri. ",			
        "max_lt_min":"Erradi maxioma ezin da minimoa baino txikiagoa ezarri. ",			
        "no_geojson":"Ez da GeoJSON bat ere zehaztu",			
        "unsupported_lang":"Euskarririk gabeko hizkuntza bat ezarri da",			
    },				
    "cambioIdioma":{			
        "esp":"Espainiarra",			
        "ing":"Ingelesa",	
        "cat": "katalana",
        "gal": "galegoa",
        "eus":"euskara",	
        "contenedor":"Hizkuntza aldaketa",	
        "divIdioma": "bistaratzeko hizkuntza"	
    }				
}				
