var diccGallego = {	
        "location":{
            "error":"O control localización non acepta http. Debe empregar https.",
            "title":"Obter localización actual",
        },	
        "layerswitcher":{
            "title":"Selector de capas",
        },	
        "scale":{
            "title":"Escala",
            "scale":"Escala",
            "level":"Nivel",
        },	
        "getfeatureinfo":{
            "info":"Información",
            "title":"Consultar capa",
            "no_info":"Non existe información asociada",
            "info_of":"Información de",
            "unsupported_format":"Formato non soportado",
        },	
        "wmcselector":{
            "title":"Selector de contextos",
        },	
        "rotate":{
            "title":"Xirar ao norte",
        },	
        "mouse":{
            "title":"Coordenadas do punteiro",
        },	
        "dialog":{
            "info":"INFORMACIÓN",
            "error":"ERRO",
            "success":"ÈXITO",
            "id_feature":"Non se indicou un ID para obter o feature",
            "invalid_type_layer":"Non se especificou un tipo válido para a capa",
            "vector_filter":"O filtro indicado non é correcto",
            "unauthorized_user":"Ocorreu un erro ao cargar a capa: Usuario non autorizado.",
            "only_one_filter":"*FeatureID e *CQL son mutuamente excluíntes. Indicar só un tipo de filtrado.",
            "any_format":"TXT, nin HTML nin *GML están soportados",
        },	
        "feature":{
            "incorrect_attributes":"Non se especificaron correctamente os atributos.",
        },	
        "exception":{
            "addto_method":"A implementación usada non posúe o método *addTo",
            "getelement_method":"A implementación usada non posúe o método  *getElement",
            "getfeatureinfo_method":"A implementación usada non pode crear controis *GetFeatureInfo",
            "mouse_method":"A implementación usada non pode crear controis *Mouse",
            "navtoolbar_method":"A implementación usada non pode crear controis *Navtoolbar",
            "overviewmap_method":"A implementación usada non pode crear controis *OverviewMap",
            "panzoom_method":"A implementación usada non pode crear controis *Panzoom",
            "panzoombar_method":"A implementación usada non pode crear controis *Panzoombar",
            "scale_method":"A implementación usada non pode crear controis *Scale",
            "scaleline_method":"A implementación usada non pode crear controis *ScaleLine",
            "wmcselector_method":"A implementación usada non pode crear controis *WMCSelector",
            "geojson_method":"A implementación usada non pode crear obxectos M.*impl.*format.*GeoJSON",
            "wkt_method":"A implementación usada non pode crear obxectos M.*impl.*format.*WKT",
            "getfeaturesbylayer_method":"A implementación usada non posúe o método *getFeaturesByLayer",
            "geojsonlayer_method":"A implementación usada non pode crear capas *GeoJSON",
            "no_param":"Non se especificou ningún parámetro",
            "no_name":"Non se especificou ningún nome",
            "kmllayer_method":"A implementación usada non pode crear capas *KML",
            "isvisible_method":"A implementación usada non posúe o método *isVisible",
            "isqueryable_methd":"A implementación usada non posúe o método *isQueryable",
            "visibility_param":"Non especificou ningún parámetro de visibilidade",
            "setvisible_method":"A implementación usada non posúe o método *setVisible",
            "inrange_method":"A implementación usada non posúe o método *inRange",
            "mapbox_method":"A implementación usada non pode crear capas *Mapbox",
            "osm_method":"A implementación usada non pode crear capas *OSM",
            "vectorlayer_method":"A implementación usada non pode crear capas Vector",
            "wfslayer_method":"A implementación usada non pode crear capas *WFS",
            "wmclayer_method":"A implementación usada non pode crear capas *WMC",
            "select_method":"A implementación usada non posúe o método *select",
            "unselect_method":"A implementación usada non posúe o método  *unselect",
            "constructor_impl":"A implementación usada non posúe un construtor.",
            "getlayers_method":"A implementación usada non posúe o método *getLayers.",
            "getbaselayers_method":"A implementación usada non posúe o método *getBaseLayers.",
            "addlayers_method":"A implementación usada non posúe o método *addLayers.",
            "removelayers_method":"A implementación usada non posúe o método *removeLayers.",
            "getwmc_method":"A implementación usada non posúe o método *getWMC.",
            "addwmc_method":"A implementación usada non posúe o método *addWMC.",
            "removewmc_method":"A implementación usada non posúe o método *removeWMC.",
            "getkml_method":"A implementación usada non posúe o método *getKML.",
            "addkml_method":"A implementación usada non posúe o método*addKML.",
            "removekml_method":"A implementación usada non posúe o método *removeKML.",
            "getwms_method":"A implementación usada non posúe o método *getWMS.",
            "addwms_method":"A implementación usada non posúe o método *addWMS.",
            "removewms_method":"A implementación usada non posúe o método *removeWMS.",
            "getwfs_method":"A implementación usada non posúe o método *getWFS.",
            "getgeojson_method":"A implementación usada non posúe o método *getGeoJSON.",
            "addwfs_method":"A implementación usada non posúe o método *addWFS.",
            "removewfs_method":"A implementación usada non posúe o método *removeWFS.",
            "getwmts_method":"A implementación usada non posúe o método *getWMTS.",
            "addwmts_method":"A implementación usada non posúe o método *addWMTS.",
            "removewmts_method":"A implementación usada non posúe o método *removeWMTS.",
            "getmbtiles_method":"A implementación usada non posúe o método *getMBtiles.",
            "getxyzs_method":"A implementación usada non posúe o método *getXYZs.",
            "gettms_method":"A implementación usada non posúe o método *getTMS.",
            "getcontrols_method":"A implementación usada non posúe o método *getControls.",
            "addcontrols_method":"A implementación usada non posúe o método *addControls.",
            "remove_control":"Non especificou ningún control para eliminar.",
            "removecontrol_method":"A implementación usada non posúe o método *removeControls.",
            "setmaxextent_method":"A implementación usada non posúe o método *setMaxExtent.",
            "getbbox_method":"A implementación usada non posúe o método *getBbox.",
            "no_bbox":"Non se especificou ningún *bbox.",
            "setbbox_method":"A implementación usada non posúe o método *setBbox.",
            "incorrect_bbox_format":"O formato do parámetro *bbox non é o correcto.",
            "getzoom_method":"A implementación usada non posúe o método *getZoom.",
            "no_zoom":"Non se especificou ningún zoom.",
            "setzoom_method":"A implementación usada non posúe o método *setZoom.",
            "getcenter_method":"A implementación usada non posúe o método *getCenter.",
            "setcenter_method":"La implementació usada no posseeix el mètode *setCenter.",
            "getresolutions_method":"A implementación usada non posúe o método *getResolutions.",
            "no_resolutions":"Non se especificou ningunha resolución.",
            "setresolutions_method":"A implementación usada non posúe o método *setResolutions.",
            "getscale_method":"A implementación usada non posúe o método *getScale.",
            "getprojection_method":"A implementación usada non posúe o método *getProjection.",
            "no_projection":"Non especificou ningunha proxección.",
            "setprojection_method":"A implementación usada non posúe o método *setProjection.",
            "no_plugins":"Non especificou ningún *plugin.",
            "no_add_plugin_to_map":"O *plugin non pode engadirse ao mapa.",
            "no_plugin_to_remove":"Non se especificou ningún *plugin a eliminar.",
            "destroy_method":"A implementación usada non posúe o método *destroy.",
            "addlabel_method":"A implementación usada non posúe o método *addLabel.",
            "no_point":"Non se especificou ningún punto.",
            "remove_control_from_panel":"Debe eliminar os controis do panel previamente.",
            "getcontainer_method":"A implementación usada non posúe o método  *getContainer.",
            "getmapimpl_method":"A implementación usada non posúe o método *getMapImpl.",
            "removepopup_method":"A implementación usada non posúe o método *removePopup.",
            "no_popup":"Non se especificou ningún *popup.",
            "invalid_popup":"O *popup especificadp non é vàlido.",
            "no_maxextent":"Non se especificou ningún *maxExtent",
            "must_be_document":"*doc.*nodeType debe ser de tipo *DOCUMENT",
            "no_service_response":"Non houbo resposta do servizo",
            "no_kml_response":"Non houbo resposta do *KML",
            "no_getfeature_response":"Non houbo resposta na operación *GetFeature",
            "no_map":"Non se especificou *ningun mapa",
            "layerswitcher_method":"A implementación usada non pode crear controis *LayerSwitcher",
            "location_method":"A implementación usada non pode crear controis *Location",
            "wms_method":"A implementación usada non pode crear capas *WMS",
            "wmts_method":"A implementación usada non pode crear capas *WMTS",
            "no_impl":"Non se especificou ningunha implementación",
            "no_container":"Non especificou ningún parámetro contedor",
            "no_id_container":"Non existe ningún contedor co id especificado",
            "no_center":"Non especificou ningún parámetro *center",
            "no_attr_name":"Non especificou o nome do atributo",
            "no_empty":"O nome de atributo non pode ser nulo. Especifique cadea ou función",
            "invalid_center_param":"O formato do parámetro *center non é correcto",
            "invalid_maxextent_param":"O formato do parámetro *maxExtent non é correcto",
            "invalid_resolutions_param":"O formato do parámetro *resolutions non é correcto",
            "invalid_zoom_param":"O formato do parámetro *zoom non é correcto",
            "min_gt_max":"Non pode establecerse un radio mínimo maior que o máximo.",
            "max_lt_min":"Non pode establecerse un radio máximo menor que o mínimo.",
            "no_geojson":"Non se especificou ningún *GeoJSON",
            "unsupported_lang":"Estableceuse un idioma sen soporte",
        },	
        "cambioIdioma":{
            "esp":"Español",
            "ing":"Inglés",
            "cat": "catalan",
            "gal": "galego",
            "eus": "euskera",
            "contenedor":"Cambio de idioma",
            "divIdioma": "Idioma del visualizador"
        }	
    }	
    